### ISSUE TITLE
Missing `marble.png` file in images

### ISSUE THREAD

**Issue by mishaschwartz** [DACCS-Climate/daccs-project-website#6]
This file is referenced here: https://github.com/DACCS-Climate/daccs-project-website/blob/main/templates/site/index.html#L51
but does not exist

**Comment by alexandercyu** [comment]
I must have forgot to push the image when I made the repo. Should I add it to the main or remove the reference in the main and include it in another branch?

**Comment by mishaschwartz** [comment]
Make a pull request that resolves this issue please.

To clarify: create a pull request that adds the marble.png file to the images folder
