### ISSUE TITLE
Be consistent with tabs and spacing 

### ISSUE THREAD

**Issue by mishaschwartz** [DACCS-Climate/daccs-project-website#9]
In index.html:
  - some indentations are 2 spaces, others are 4, 12, 16 (?)
  - lots of empty lines

**Comment by alexandercyu** [comment]
I just press Tab and let it set the spacing automatically.  I don't know why it's different sometimes.

**Comment by alexandercyu** [comment]
>lots of empty lines

Are the empty lines in the opening paragraph?  That's where I used Enter a lot to move the text to the next line to keep it within the limit of characters per line.

**Comment by mishaschwartz** [comment]
https://github.com/DACCS-Climate/daccs-project-website/blob/main/templates/site/index.html#L24-L26
https://github.com/DACCS-Climate/daccs-project-website/blob/main/templates/site/index.html#L38-L39
https://github.com/DACCS-Climate/daccs-project-website/blob/main/templates/site/index.html#L41-L44

**Comment by alexandercyu** [comment]
Those have been taken out in the latest push

**Comment by mishaschwartz** [comment]
> Those have been taken out in the latest push

Great, please update that PRs description then to ensure that it resolves this issue when it is merged
